from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from uuid import UUID

class EventBase(BaseModel):
    symbol: str = Field(..., description="The stock symbol (e.g., 'AAPL').")
    event_type: str = Field(..., description="The normalized event type.")
    event_date: datetime = Field(..., description="The date and time of the event.")
    title: str = Field(..., description="A descriptive title for the event.")
    details: Dict[str, Any] = Field(..., description="Provider-specific details.")

class EventCreate(EventBase):
    source: str = Field(..., description="The provider's name.")
    provider_event_id: str = Field(..., description="The original event ID from the provider.")

class Event(EventBase):
    id: UUID = Field(..., description="A unique identifier generated by our service.")
    created_at: datetime = Field(..., description="Timestamp of when the event was first created.")
    updated_at: datetime = Field(..., description="Timestamp of when the event was last updated.")

    class Config:
        from_attributes = True

class EventResponse(BaseModel):
    data: List[Event]
    total: int
    limit: int
    offset: int
    has_more: bool

class SyncRequest(BaseModel):
    symbols: List[str]
    force: bool = False

class SyncResponse(BaseModel):
    status: str
    symbols_synced: List[str]
    symbols_skipped: List[str]
    events_created: int
    events_updated: int
    errors: List[str]

class HealthResponse(BaseModel):
    status: str
    redis: str
    db: str
