from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class EventBase(BaseModel):
    symbol: str = Field(..., description="The stock symbol (e.g., 'AAPL').")
    event_type: str = Field(..., description="The normalized event type.")
    event_date: datetime = Field(..., description="The date and time of the event.")
    title: str = Field(..., description="A descriptive title for the event.")
    details: dict[str, Any] = Field(..., description="Provider-specific details.")


class EventCreate(EventBase):
    source: str = Field(..., description="The provider's name.")
    provider_event_id: str = Field(..., description="The original event ID from the provider.")


class Event(EventBase):
    id: UUID = Field(..., description="A unique identifier generated by our service.")
    created_at: datetime = Field(..., description="Timestamp of when the event was first created.")
    updated_at: datetime = Field(..., description="Timestamp of when the event was last updated.")

    class Config:
        from_attributes = True


class EventResponse(BaseModel):
    data: list[Event]
    total: int
    limit: int
    offset: int
    has_more: bool


class SyncRequest(BaseModel):
    symbols: list[str]
    force: bool = False


class SyncResponse(BaseModel):
    status: str
    symbols_synced: list[str]
    symbols_skipped: list[str]
    events_created: int
    events_updated: int
    errors: list[str]


class HealthResponse(BaseModel):
    status: str
    redis: str
    db: str
